export const GET_CARDS = 'GET_CARDS';
export const API = 'API';
export const SET_CARDS_TO_STATE = 'SET_CARDS_TO_STATE';
export const SET_PUBS_TO_STATE = 'SET_PUBS_TO_STATE';
export const SET_NEW_PUB = 'SET_NEW_PUB';

export const SET_MODAL_DATA = 'SET_MODAL_DATA';

export const postsConstants = {
  UPDATE_PROFILE_POSTS: 'UPDATE_PROFILE_POSTS',
  UPDATE_GENERAL_POSTS: 'UPDATE_GENERAL_POSTS',
  ADD_NEW_POST: 'ADD_NEW_POST',
  REMOVE_POST: 'REMOVE_POST',
  SHOW_POST_FORM: 'SHOW_POST_FORM',
  POST_SECTION_VISIBLE: 'POST_SECTION_VISIBLE',
  SET_POST_FORM: 'SET_POST_FORM',
  UPDATE_POST_CONTENT: 'UPDATE_POST_CONTENT',
  SET_NEW_POSTS_AVAILABLE: 'SET_NEW_POSTS_AVAILABLE',
};

export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  SET_USERNAME_NAVBAR: 'SET_USERNAME_NAVBAR',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_USER_PUBS: 'SET_USER_PUBS',
  DELETE_USER_DATA: 'DELETE_USER_DATA',
};

export const snackbarConstants = {
  SET_ALL_DATA: 'SET_ALL_DATA',
  SET_SHOW: 'SET_SHOW',
  SET_LABEL: 'SET_LABEL',
  SET_TYPE: 'SET_TYPE',
};
